---
# apt-get install -y apt-transport-https ca-certificates curl software-properties-common
- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      # allowing you to add external HTTPS sources to your APT sources list.
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - curl

# curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
- name: Add Google Cloud public key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

# sudo add-apt-repository "deb https://packages.cloud.google.com/apt cloud-sdk main"
- name: Set up the Cloud SDK distribution repository
  apt_repository:
    repo: 'deb https://packages.cloud.google.com/apt cloud-sdk main'
    state: present

# sudo apt-get update && sudo apt-get install google-cloud-sdk
- name: Install Cloud SDK
  apt:
    name: google-cloud-sdk
    state: present
    update_cache: yes